project:
  type: website

website:
  title: "ENGJ20"
  page-navigation: true
  page-footer: "Copyright 2026, Mauro Alixandrini"
  navbar:
    left:
      - href: index.qmd
        text: Programa
      - text: Bloco 1
        menu:
        - href: logica_programacao_aula1.ipynb
          text: Aula 1
        - href: estruturas_dados_cartografia_aula2.ipynb
          text: Aula 2
        - href: aula_listas_python_cartografia_aula3.md
          text: Aula 3  
      - text: Bloco 2
        menu:
        - text: Aula 4
          href: about.qmd 
      - text: Bloco 3
        menu: 
        - text: Aula 10
          href: about.qmd
      - href: about.qmd
        text: Sobre 
  sidebar:
    logo: logo_labfsr.png
    contents:
      - href: index.qmd
        text: Programa do Curso
      - href: logica_programacao_aula1.ipynb
        text: Aula 1 - Lógica de Programação
      - href: estruturas_dados_cartografia_aula2.ipynb
        text: Aula 2 - Estruturas Básicas
      - href: aula_listas_python_cartografia_aula3.md
        text: Aula 3 - Utilizando Listas     
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



